phone_inventory: "CMU-39 to Style-BERT-VITS2 EN_SYMBOLS"
mapping:
  AA: "aa"
  AE: "ae"
  AH: "ah"
  AO: "ao"
  AW: "aw"
  AY: "ay"
  B: "b"
  CH: "ch"
  D: "d"
  DH: "dh"
  EH: "eh"
  ER: "er"
  EY: "ey"
  F: "f"
  G: "g"
  HH: "hh"
  IH: "ih"
  IY: "iy"
  JH: "jh"
  K: "k"
  L: "l"
  M: "m"
  N: "n"
  NG: "ng"
  OW: "ow"
  OY: "oy"
  P: "p"
  R: "r"
  S: "s"
  SH: "sh"
  T: "t"
  TH: "th"
  UH: "uh"
  UW: "uw"
  V: "V"
  W: "w"
  Y: "y"
  Z: "z"
  ZH: "zh"
